-- tao database
USE master
GO
IF DB_ID('QLBH') IS NOT NULL DROP DATABASE QLBH
GO	
CREATE DATABASE QLBH
GO
USE QLBH
GO
-- tao bang
--1. KhachHang(MaKH,TenKH,NgaySinh,DiaChi,NgayDK,MaND,DiemTichLuy)
--2. Loai_Nguoi_Dung(MaND,TenLoaiKH,DiemTichLuyCanThiet)
--16. CS_KhachHangThanThiet(MaCSKH,TongTienHoaDonToiThieu,HeSoGiamGia,NgayBD, NgayKT)
--18. KhachHang_ChinhSach(CSMaND,CSMaCSKH)
--7. KhachHang_HoaDon(MaHD,MaKH,Diem)

--3. NhanVien(MaNV,TenNV,UserID)
--4. TaiKhoan(UserID,pass,QuyenHan,NguoiTao,NgayTao)
--5. Loai_TaiKhoan(MaLTK,TenLoai)

--6. HoaDon(MaHD,NgayLap,MaNV,ThanhTien,TienKhachDua,TienHoanLai,VAT)
--8. CT_HoaDon(MaHD,MaMH,SoLuong,Gia,GiamGia)

--9. MatHang(MaMH,TenMH,DonVi,GiaBan,GiaNhap,MaKM,MaLoai,TrangThai)
--10. Loai_MH(MaLoaiMH,TenLoai,SoLuongTonToiDa)
--11. CS_KhuyenMai(MaCS,HeSoGiam,NgayBD,NgayKT)
--12. Kho(MaKho,DienTich,ViTri)
--13. Quay(MaQuay,ViTri)
--14. MatHang_Quay(MaMH,MaQuay,SoLuong)
--15. MatHang_Kho(MaMH,MaKho,SoLuong)

--17. DoanhThu(Ngay,TongDoanhThu,TongchiPhi,SoHoaDon,SLKhachHangMoi)
--19. TrangThai_HangHoa(MaTT, TenTT)

--20. NhaPhanPhoi(MaNPP,TenNPP, SDTNPP, DiaChiNPP)
--21. PhieuNhap(MaPhieuNhap, MaNhanVien, NPP, NgayNhap, TongGiaTri)
--22. CT_PhieuNhap(MaCTPN, MaPN, MatHang, SoLuong, DonGiaNhap, ThanhTien)

--1
CREATE TABLE KHACH_HANG
(
	MaKH INT IDENTITY PRIMARY KEY,
	TenKH NVARCHAR(50) NOT NULL,
	NgaySinh DATE ,
	DiaChi NVARCHAR(100) NOT NULL DEFAULT N'Chưa có địa chỉ',
	NgayDK DATE NOT NULL DEFAULT GETDATE(),
	MaND INT NOT NULL DEFAULT 1, -- Mức người dùng thấp nhất
	DiemTichLuy INT NOT NULL DEFAULT 0
)
GO
--2
CREATE TABLE LOAI_NGUOI_DUNG
(
	MaND INT IDENTITY PRIMARY KEY,
	TenLoaiND NVARCHAR(50) NOT NULL,
	DiemTichLuyCanThiet INT NOT NULL DEFAULT 0,
	MaCSKH INT
)
GO
--3
CREATE TABLE NHAN_VIEN
(
	MaNV INT IDENTITY PRIMARY KEY,
	TenNV NVARCHAR(50) NOT NULL,
	UserID VARCHAR(50)
)
GO
--4
CREATE TABLE TAI_KHOAN
(
	UserID VARCHAR(50) PRIMARY KEY,
	Pass VARCHAR(100) NOT NULL,
	MaLoai VARCHAR(10) NOT NULL,
	NguoiTao INT NOT NULL,
	NgayTao DATE NOT NULL DEFAULT GETDATE()
)
GO
--5
CREATE TABLE LOAI_TAIKHOAN
(
	MaLTK VARCHAR(10) PRIMARY KEY,
	TenLoai NVARCHAR(20) NOT NULL
)
GO
--6
CREATE TABLE HOA_DON
(
	MaHD INT PRIMARY KEY,
	NgayLap DATE NOT NULL DEFAULT GETDATE(),
	MaNV INT,
	ThanhTien MONEY NOT NULL DEFAULT 0,
	VAT MONEY DEFAULT 0.1,
	TienKhachDua MONEY,
	TienHoanLai MONEY
)
GO
--7
CREATE TABLE KHACHHANG_HOADON
(
	MaHD INT NOT NULL,
	MaKH INT NOT NULL,
	DiemTichLuyCongThem INT,
	CONSTRAINT PK_KHACHHANG_HOADON PRIMARY KEY(MaHD,MaKH),
	CONSTRAINT FK_KHACHHANG_HOADON FOREIGN KEY(MaKH) REFERENCES dbo.KHACH_HANG(MaKH),
	CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(MaHD) REFERENCES dbo.HOA_DON(MaHD)	
)
GO
--8
CREATE TABLE CT_HOADON
(
	MaHD INT NOT NULL,
	MaMH INT NOT NULL,
	SoLuong INT NOT NULL DEFAULT 1,
	DonGia INT NOT NULL,
	HeSoGiam FLOAT,
	ThanhTien MONEY NOT NULL DEFAULT 0,
	CONSTRAINT PK_CT_HOADON PRIMARY KEY(MaHD,MaMH),
	CONSTRAINT FK_CT_HOADON FOREIGN KEY(MaHD) REFERENCES dbo.HOA_DON(MaHD)
)
GO
--9
CREATE TABLE MAT_HANG
(
	MaMH INT IDENTITY PRIMARY KEY,
	TenMH NVARCHAR(50) NOT NULL,
	DonVi NVARCHAR(20) NOT NULL,
	GiaBan MONEY NOT NULL DEFAULT 0,
	GiaNhap MONEY NOT NULL DEFAULT 0,
	MaCSKM INT,
	MaLoaiMH INT NOT NULL,
	TrangThai INT NOT NULL,
	NhaPhanPhoi INT NOT NULL
)
GO
--10
CREATE TABLE LOAI_MH
(
	MaLoaiMH INT IDENTITY PRIMARY KEY,
	TenLoai NVARCHAR(50) NOT NULL DEFAULT N'Chưa có tên',
	SLToiThieuTrongKho INT NOT NULL DEFAULT 100,
	SLToiThieuTrongQuay INT NOT NULL DEFAULT 100
)
GO
--11
CREATE TABLE CS_KHUYENMAI
(
	MaCSKM INT IDENTITY PRIMARY KEY,
	HeSoGiam FLOAT NOT NULL DEFAULT 1,
	NgayBD DATE NOT NULL DEFAULT GETDATE(),
	NgayKT DATE
)
GO
--12
CREATE TABLE KHO
(
	MaKho INT IDENTITY PRIMARY KEY,
	TenKho NVARCHAR(200)
)
GO
--13
CREATE TABLE QUAY
(
	MaQuay INT IDENTITY PRIMARY KEY,
	ViTri NVARCHAR(100) NOT NULL 
)
GO
--14
CREATE TABLE MATHANG_QUAY
(
	MaMH INT NOT NULL,
	MaQuay INT NOT NULL,
	SoLuong INT,
	CONSTRAINT FK_MATHANG_QUAY FOREIGN KEY(MaMH) REFERENCES dbo.MAT_HANG(MaMH),
	CONSTRAINT FK_QUAY_MATHANG FOREIGN KEY(MaQuay) REFERENCES dbo.QUAY(MaQuay)
)
GO
--15
CREATE TABLE MATHANG_KHO
(
	MaMH INT NOT NULL,
	MaKho INT NOT NULL,
	SoLuong INT,
	CONSTRAINT FK_MATHANG_KHO FOREIGN KEY(MaMH) REFERENCES dbo.MAT_HANG(MaMH),
	CONSTRAINT FK_KHO_MATHANG FOREIGN KEY(MaKho) REFERENCES dbo.KHO(MaKho)
)
GO
--16
CREATE TABLE CS_KHACHHANG
(
	MaCSKH INT IDENTITY PRIMARY KEY,
	TenChinhSach NVARCHAR(50) NOT NULL,
	TongTienHoaDonToiThieu MONEY NOT NULL DEFAULT 0,
	HeSoGiamGia FLOAT DEFAULT 1,
	DiemCongToiThieu INT DEFAULT 1
)
GO
--17.1
CREATE TABLE DOANHTHU_NGAY
(
	Ngay DATE NOT NULL PRIMARY KEY,
	TongDoanhThu MONEY NOT NULL DEFAULT 0,
	SoLuongHoaDon INT NOT NULL DEFAULT 0,
	SLKhachHangMoi INT NOT NULL DEFAULT 0
)
GO
--17.2
CREATE TABLE DOANHTHU_THANG
(
	Thang INT NOT NULL PRIMARY KEY,
	Nam INT NOT NULL,
	TongDoanhThu MONEY NOT NULL DEFAULT 0,
	SoLuongHoaDon INT NOT NULL DEFAULT 0,
	SLKhachHangMoi INT NOT NULL DEFAULT 0
)
GO
--17.3
CREATE TABLE DOANHTHU_NAM
(
	Nam INT NOT NULL PRIMARY KEY,
	TongDoanhThu MONEY NOT NULL DEFAULT 0,
	SoLuongHoaDon INT NOT NULL DEFAULT 0,
	SLKhachHangMoi INT NOT NULL DEFAULT 0
)
GO
--18

--19.
CREATE TABLE TRANGTHAI_MATHANG
(
	MaTT INT IDENTITY PRIMARY KEY, 
	TenTT NVARCHAR(50)
)
GO	
--20.
CREATE TABLE NHAPHANPHOI
(
	MaNPP INT IDENTITY PRIMARY KEY,
	TenNPP NVARCHAR(50) NOT NULL, 
	SDTNPP VARCHAR(15), 
	DiaChiNPP NVARCHAR(100)
)
--21. 
CREATE TABLE PHIEU_NHAP
(
	MaPhieuNhap INT IDENTITY PRIMARY KEY, 
	MaNhanVien INT NOT NULL, 
	NPP INT NOT NULL, 
	NgayNhap DATE NOT NULL DEFAULT GETDATE(), 
	TongGiaTri MONEY
)
GO
--22. 
CREATE TABLE CT_PHIEUNHAP
(
	MaCTPN INT IDENTITY PRIMARY KEY,		
	MaPN INT NOT NULL, 
	MatHang INT NOT NULL, 
	SoLuong INT NOT NULL DEFAULT 1, 
	DonGiaNhap MONEY NOT NULL, 
	ThanhTien MONEY NOT NULL

)

-- tao khoa ngoai
--1. tạo khóa ngoại tại bảng khách hàng thuộc loại người dùng nào
ALTER TABLE dbo.KHACH_HANG ADD
CONSTRAINT FK_KHACHHANG_LOAINGUOIDUNG
FOREIGN KEY (MaND) REFERENCES dbo.LOAI_NGUOI_DUNG(MaND)
GO
--2. tạo khóa ngoại bảng mat hang thuộc loại mặt hằng nào
ALTER TABLE dbo.MAT_HANG ADD
CONSTRAINT FK_MATHANG_LOAIMH
FOREIGN KEY (MaLoaiMH)
REFERENCES dbo.LOAI_MH(MaLoaiMH)
GO
--3. tạo khóa ngoại bảng mặt hàng có chính sách khuyễn mãi gì
ALTER TABLE dbo.MAT_HANG ADD
CONSTRAINT FK_MATHANG_CSKM
FOREIGN KEY(MaCSKM)
REFERENCES dbo.CS_KHUYENMAI(MaCSKM)
GO
--4. tạo khóa ngoại bảng loại người dùng
ALTER TABLE dbo.LOAI_NGUOI_DUNG ADD
CONSTRAINT FK_LOAINGUOIDUNG_CS
FOREIGN KEY(MaCSKH) 
REFERENCES dbo.CS_KHACHHANG(MaCSKH)
GO
--5. tạo khóa ngoại bảng chi tiết hóa đơn
ALTER TABLE dbo.CT_HOADON ADD
CONSTRAINT FK_CT_HOADON_MATHANG 
FOREIGN KEY (MaMH)
REFERENCES dbo.MAT_HANG(MaMH)
GO
--6. tạo khóa ngoại hóa đơn
ALTER TABLE dbo.HOA_DON ADD
CONSTRAINT FK_HOADON_NHANVIEN 
FOREIGN KEY (MaNV)
REFERENCES dbo.NHAN_VIEN(MaNV)
GO
--7. tạo khóa ngoại bảng nhân viên
ALTER TABLE dbo.NHAN_VIEN ADD
CONSTRAINT FK_NHANVIEN_TAIKHOAN
FOREIGN KEY (UserID)
REFERENCES dbo.TAI_KHOAN(UserID)
GO
--8. tạo khóa ngoại bảng mặt hàng, tình trạng mặt hàng đang kinh doanh, không kinh doanh...
ALTER TABLE dbo.MAT_HANG ADD
CONSTRAINT FK_MATHANG_TRANGTHAI
FOREIGN KEY (TrangThai)
REFERENCES dbo.TRANGTHAI_MATHANG
GO 
--9. tạo khóa ngoại bảng tài khoản, quyền đăng nhập vào những màn hình theo quyền
ALTER TABLE dbo.TAI_KHOAN ADD
CONSTRAINT FK_TAIKHOAN_LOAITK
FOREIGN KEY (MaLoai)
REFERENCES dbo.LOAI_TAIKHOAN(MaLTK)
GO
--10. tai khoan do ai tao
ALTER TABLE dbo.TAI_KHOAN ADD
CONSTRAINT FK_TAIKHOAN_NGUOITAO
FOREIGN KEY (NguoiTao)
REFERENCES dbo.NHAN_VIEN(MaNV)
GO
--13. tao khoa ngoai chi tiet phieu nhap
ALTER TABLE dbo.CT_PHIEUNHAP ADD
CONSTRAINT FK_CTPN_PHIEUNHAP
FOREIGN KEY (MaPN)
REFERENCES dbo.PHIEU_NHAP(MaPhieuNhap),
CONSTRAINT FK_CTPN_MATHANG
FOREIGN KEY (MatHang)
REFERENCES dbo.MAT_HANG(MaMH)
GO
--14. tao khoa ngoai phieu nhap
ALTER TABLE dbo.PHIEU_NHAP ADD
CONSTRAINT FK_PHIEUNHAP_NHANVIEN
FOREIGN KEY (MaNhanVien)
REFERENCES dbo.NHAN_VIEN(MaNV),
CONSTRAINT FK_PHIEUNHAP_NPP
FOREIGN KEY (NPP)
REFERENCES dbo.NHAPHANPHOI(MaNPP)
GO
--15. bang mat hang nhà phân phối
ALTER TABLE dbo.MAT_HANG ADD
CONSTRAINT FK_MATHANG_NHAPHANPHOI
FOREIGN KEY (NhaPhanPhoi)
REFERENCES dbo.NHAPHANPHOI(MaNPP)
GO